### ISSUE TITLE
Specifying `-j 4` in all commands ?

### ISSUE THREAD

**Issue by AltGr** [coq-io/opam-website#2]
Glad to see another opam site pop around! Great work :)

Just a small remark here: all install instructions include `-j 4` ([code](https://github.com/coq-io/opam-website/blob/cdf7a3b4b7059b395b5c89f7492efa91f63b9ca6/src/View.v#L161)). This made sense for earlier opam releases, but current versions get your number of cores and initialise to that minus one as the `--jobs` parameter (it's stored in `~/.opam/config:jobs`), so it shouldn't be needed anymore.

**Comment by clarus** [comment]
Thanks! Good to know for the `--jobs` option, I will update all my documentations.
