### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by gares** [coq-io/opam-website#3]
Dear Guillaume, as you may have read on coq-club we have finally announced the OPAM archive of Coq packages (better late than never ;-).

As far as I can tell, `https://coq.io/opam` is a nice example of what `coq.io` can do, but this is written nowhere, and many people think this it is an official service maintained by the Coq team, which is not.

Would you mind making it explicit?  I mean something like: "This website shows what can be done with the coq.io framework. The official index of Coq packages is at `https://coq.inria.fr/opam/www/`"

Also concerned: @maximedenes

**Comment by clarus** [comment]
Hi, yes I have read the announcement, good job! :) Sure, to make it explicit I added the disclaimer in this commit https://github.com/coq-io/opam-website/commit/b07be3915dd83940596ae886ce535819cd4a5999 It is also visible online.

**Comment by gares** [comment]
Thanks!
